version: '2'
services:
    leadlet_api-app:
        image: leadlet_api
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://leadlet_api-mysql:3306/leadlet_api?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    leadlet_api-mysql:
        extends:
            file: mysql.yml
            service: leadlet_api-mysql
