version: '2'
services:
    leadlet_api-mysql:
        image: mysql:5.7.18
        # volumes:
        #     - ~/volumes/jhipster/leadlet_api/mysql/:/var/lib/mysql/
        volumes:
            - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
        environment:
            - MYSQL_USER=leadlet
            - MYSQL_PASSWORD=leadlet_123
            - MYSQL_DATABASE=leadlet_api
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        ports:
            - 3306:3306

    leadlet-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        container_name: elasticsearch
        environment:
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./config/logstash:/usr/share/logstash/pipeline/
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.2
        ports:
            - 5601:5601

volumes:
  mycustom.cnf:
  esdata1:
    driver: local
