version: '2'
services:
    leadlet_api-mysql:
        image: mysql:5.7.18
        # volumes:
        #     - ~/volumes/jhipster/leadlet_api/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=leadlet
            - MYSQL_PASSWORD=leadlet_123
            - MYSQL_DATABASE=leadlet_api
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        ports:
            - 3306:3306
